DROP TABLE IF EXISTS Region;
DROP TABLE IF EXISTS Rank;
DROP TABLE IF EXISTS Role;
DROP TABLE IF EXISTS Ability;
DROP TABLE IF EXISTS Weapon;
DROP TABLE IF EXISTS Gamemode;
DROP TABLE IF EXISTS Map;

CREATE TABLE Region (
	RegionID INTEGER PRIMARY KEY AUTOINCREMENT,
	RegionName VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Rank (
	RankID INTEGER PRIMARY KEY AUTOINCREMENT,
	RankName VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Role (
	RoleID INTEGER PRIMARY KEY AUTOINCREMENT,
	RoleName VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Ability (
	AbilityID INTEGER PRIMARY KEY AUTOINCREMENT,
	AbilityName VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Weapon (
	WeaponID INTEGER PRIMARY KEY AUTOINCREMENT,
	WeaponName VARCHAR(50) NOT NULL UNIQUE,
	WeaponType VARCHAR(50)
);

CREATE TABLE Gamemode (
	GamemodeID INTEGER PRIMARY KEY AUTOINCREMENT,
	GamemodeName VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Map (
	MapID INTEGER PRIMARY KEY AUTOINCREMENT,
	MapName VARCHAR(50) NOT NULL UNIQUE
);
